In [64]:
#kaggle dataset download -d username/filename

Step 1: Data Exploration and loading

In [65]:
#importing the dependencies
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

In [66]:


df = pd.read_csv(r"C:\Users\HP\Desktop\walmart-sales-analysis\Walmart.csv",encoding_errors= 'ignore')
print(df)

       invoice_id   Branch         City                category unit_price  \
0               1  WALM003  San Antonio       Health and beauty     $74.69
1               2  WALM048    Harlingen  Electronic accessories     $15.28
2               3  WALM067  Haltom City      Home and lifestyle     $46.33
3               4  WALM064      Bedford       Health and beauty     $58.22
4               5  WALM013       Irving       Sports and travel     $86.31
...           ...      ...          ...                     ...        ...
10046        9996  WALM056      Rowlett     Fashion accessories        $37
10047        9997  WALM030   Richardson      Home and lifestyle        $58
10048        9998  WALM050     Victoria     Fashion accessories        $52
10049        9999  WALM032        Tyler      Home and lifestyle        $79
10050       10000  WALM069     Rockwall     Fashion accessories        $62

       quantity      date      time payment_method  rating  profit_margin
0           7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1           5.0  08/03/19  10:29:00           Cash     9.6           0.48
2           7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3           8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4           7.0  08/02/19  10:37:00        Ewallet     5.3           0.48
...         ...       ...       ...            ...     ...            ...
10046       3.0  03/08/23  10:10:00           Cash     3.0           0.33
10047       2.0  22/02/21  14:20:00           Cash     7.0           0.48
10048       3.0  15/06/23  16:00:00    Credit card     4.0           0.48
10049       2.0  25/02/21  12:25:00           Cash     7.0           0.48
10050       3.0  26/09/20   9:48:00           Cash     3.0           0.33

[10051 rows x 11 columns]

In [67]:
#total rows and columns
df.shape

(10051, 11)

In [68]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [69]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [70]:
df.describe()#stats

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [72]:

df.duplicated().sum() #total of 51 duplicates record

np.int64(51)

In [73]:
#checking the missing values
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [74]:
#removing the duplicates
df.drop_duplicates(inplace= True)

In [75]:
#checking again the duplicates
df.duplicated().sum() #got 0

np.int64(0)

In [76]:
#dropping for null values
df.dropna(inplace = True)
df

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,WALM056,Rowlett,Fashion accessories,$37,3.0,03/08/23,10:10:00,Cash,3.0,0.33
9996,9997,WALM030,Richardson,Home and lifestyle,$58,2.0,22/02/21,14:20:00,Cash,7.0,0.48
9997,9998,WALM050,Victoria,Fashion accessories,$52,3.0,15/06/23,16:00:00,Credit card,4.0,0.48
9998,9999,WALM032,Tyler,Home and lifestyle,$79,2.0,25/02/21,12:25:00,Cash,7.0,0.48
9999,10000,WALM069,Rockwall,Fashion accessories,$62,3.0,26/09/20,9:48:00,Cash,3.0,0.33

In [77]:
df.isna().sum() #hence no null

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [78]:
df.shape

(9969, 11)

In [79]:
#checking the unit price to int types
# df['unit_price'].astype(int)#dueto $ sign this is not convertable

In [80]:
df['unit_price']=df['unit_price'].str.replace('$','').astype(float)

In [81]:
df['unit_price'].dtypes

dtype('float64')

In [82]:
#again for the Quantity column
df['quantity'].dtypes

dtype('float64')

In [83]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price        float64
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

In [84]:
#creating the total columns
df['total']= df['unit_price']*df['quantity']
df

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,WALM056,Rowlett,Fashion accessories,37.00,3.0,03/08/23,10:10:00,Cash,3.0,0.33,111.00
9996,9997,WALM030,Richardson,Home and lifestyle,58.00,2.0,22/02/21,14:20:00,Cash,7.0,0.48,116.00
9997,9998,WALM050,Victoria,Fashion accessories,52.00,3.0,15/06/23,16:00:00,Credit card,4.0,0.48,156.00
9998,9999,WALM032,Tyler,Home and lifestyle,79.00,2.0,25/02/21,12:25:00,Cash,7.0,0.48,158.00
9999,10000,WALM069,Rockwall,Fashion accessories,62.00,3.0,26/09/20,9:48:00,Cash,3.0,0.33,186.00

In [85]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [86]:
#psql
# localhost
# user = postgres
# port= 5432
# password= ''

In [87]:
df.to_csv('walmart_clean.csv',index= False)

In [88]:
df.columns = df.columns.str.lower() 
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin', 'total'],
      dtype='str')

In [89]:
#psql connection
engine_psql = create_engine("postgresql+psycopg2://postgres:root@localhost:5432/walmart_db")

try:
    engine_psql
    print("successfully connected")
except:
    print("unable to connect")

successfully connected

In [ ]:
#importing to the db
# df.to_sql(name='walmart',con= engine_psql,if_exists='append',index=False)

DatabaseError: Execution failed on sql 'INSERT INTO walmart (invoice_id, branch, city, category, unit_price, quantity, date, time, payment_method, rating, profit_margin, total) VALUES (:invoice_id, :branch, :city, :category, :unit_price, :quantity, :date, :time, :payment_method, :rating, :profit_margin, :total)': (psycopg2.errors.UndefinedColumn) column "branch" of relation "walmart" does not exist
LINE 1: INSERT INTO walmart (invoice_id, branch, city, category, uni...
                                         ^

[SQL: INSERT INTO walmart (invoice_id, branch, city, category, unit_price, quantity, date, time, payment_method, rating, profit_margin, total) VALUES (%(invoice_id__0)s, %(branch__0)s, %(city__0)s, %(category__0)s, %(unit_price__0)s, %(quantity__0)s, %(dat ... 224472 characters truncated ... )s, %(time__999)s, %(payment_method__999)s, %(rating__999)s, %(profit_margin__999)s, %(total__999)s)]
[parameters: {'invoice_id__0': 1, 'unit_price__0': 74.69, 'city__0': 'San Antonio', 'payment_method__0': 'Ewallet', 'time__0': '13:08:00', 'profit_margin__0': 0.48, 'total__0': 522.8299999999999, 'date__0': '05/01/19', 'quantity__0': 7.0, 'category__0': 'Health and beauty', 'rating__0': 9.1, 'branch__0': 'WALM003', 'invoice_id__1': 2, 'unit_price__1': 15.28, 'city__1': 'Harlingen', 'payment_method__1': 'Cash', 'time__1': '10:29:00', 'profit_margin__1': 0.48, 'total__1': 76.39999999999999, 'date__1': '08/03/19', 'quantity__1': 5.0, 'category__1': 'Electronic accessories', 'rating__1': 9.6, 'branch__1': 'WALM048', 'invoice_id__2': 3, 'unit_price__2': 46.33, 'city__2': 'Haltom City', 'payment_method__2': 'Credit card', 'time__2': '13:23:00', 'profit_margin__2': 0.33, 'total__2': 324.31, 'date__2': '03/03/19', 'quantity__2': 7.0, 'category__2': 'Home and lifestyle', 'rating__2': 7.4, 'branch__2': 'WALM067', 'invoice_id__3': 4, 'unit_price__3': 58.22, 'city__3': 'Bedford', 'payment_method__3': 'Ewallet', 'time__3': '20:33:00', 'profit_margin__3': 0.33, 'total__3': 465.76, 'date__3': '27/01/19', 'quantity__3': 8.0, 'category__3': 'Health and beauty', 'rating__3': 8.4, 'branch__3': 'WALM064', 'invoice_id__4': 5, 'unit_price__4': 86.31 ... 11900 parameters truncated ... 'rating__995': 6.2, 'branch__995': 'WALM012', 'invoice_id__996': 997, 'unit_price__996': 97.38, 'city__996': 'Fort Worth', 'payment_method__996': 'Ewallet', 'time__996': '17:16:00', 'profit_margin__996': 0.48, 'total__996': 973.8, 'date__996': '02/03/19', 'quantity__996': 10.0, 'category__996': 'Home and lifestyle', 'rating__996': 4.4, 'branch__996': 'WALM005', 'invoice_id__997': 998, 'unit_price__997': 31.84, 'city__997': 'Mission', 'payment_method__997': 'Ewallet', 'time__997': '13:22:00', 'profit_margin__997': 0.48, 'total__997': 31.84, 'date__997': '09/02/19', 'quantity__997': 1.0, 'category__997': 'Food and beverages', 'rating__997': 7.7, 'branch__997': 'WALM041', 'invoice_id__998': 999, 'unit_price__998': 65.82, 'city__998': 'Big Spring', 'payment_method__998': 'Cash', 'time__998': '15:33:00', 'profit_margin__998': 0.33, 'total__998': 65.82, 'date__998': '22/02/19', 'quantity__998': 1.0, 'category__998': 'Home and lifestyle', 'rating__998': 4.1, 'branch__998': 'WALM095', 'invoice_id__999': 1000, 'unit_price__999': 88.34, 'city__999': 'Waco', 'payment_method__999': 'Cash', 'time__999': '13:28:00', 'profit_margin__999': 0.48, 'total__999': 618.38, 'date__999': '18/02/19', 'quantity__999': 7.0, 'category__999': 'Fashion accessories', 'rating__999': 6.6, 'branch__999': 'WALM025'}]
(Background on this error at: https://sqlalche.me/e/20/f405)