## Working with the Real Project on Weather data analysis with Python

In [1]:
#part of big data analysis
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df= pd.read_csv('weather_dataset.csv')
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

### 1. Explore the data

In [5]:
df.head() #shows the 5 number of rows from the top

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [7]:
df.shape# shows the total number of rows and total number of columns

(8784, 8)

In [9]:
df.index #index range of the dataframe

RangeIndex(start=0, stop=8784, step=1)

In [10]:
df.columns#view all columns in the dataset

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [14]:
 df.info()#dtype and checkinf the not null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [17]:
df['Weather'].unique() #chooses the unique value from the dataframe

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [18]:
df.count() #count the total number of values present in the df

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [20]:
df['Weather'].value_counts() #shows the count of the value for the particular command

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [32]:
#find all the unique 'Wind Speed' values in the data
print(df.columns)
df.rename(columns = {'Wind Speed_km/h':'Wind Speed'}, inplace = True)
df['Wind Speed'].nunique() #nunique() for every columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%', 'Wind Speed',
       'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

34

In [45]:
#find the number of times the weather is exactly clear.
count_clear = df[df['Weather'] == 'Clear'].shape[0]
print(count_clear)

1326

In [46]:
#using the sum
count_clear = (df['Weather'] == 'Clear').sum()
print(count_clear)

1326

In [53]:
#3. Find the number of times when the wind speed was exactly 4 kmh
count = df[df['Wind Speed'] == 4].value_counts().shape[0]
count

474

In [55]:
#find out the null values in the data
df.isna().sum() #findout 0 null values

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed          0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [56]:
#rename the column 'Weather' to the 'Weather condition'
df.rename(columns = {'Weather':'Weather_condition'}, inplace= True)
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa,Weather_condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [60]:
#what is the mean visibility
mean_visibility = df['Visibility_km'].mean()
mean_visibility

27.664446721311478

In [62]:
#what is the standard deviation of the Pressure
df.columns
df.Press_kPa.std()

0.8440047459486474

In [65]:
#variance of the relative humidity in this data.
df['Rel Hum_%'].var() #how much the data points are deviated from the average

286.2485501984998

In [66]:
df['Rel Hum_%']

0       86
1       87
2       89
3       88
4       88
        ..
8779    81
8780    83
8781    93
8782    89
8783    86
Name: Rel Hum_%, Length: 8784, dtype: int64

In [67]:
#find all the instance when 'Snow' was recored
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa,Weather_condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [72]:
(df['Weather_condition'] == 'Snow').sum()

390

In [76]:
df[df['Weather_condition'] =='Snow'].shape[0]

390

In [79]:
#str.contains - shows the count containing the Snow
df['Weather_condition'].str.contains('Snow').shape[0]

8784

In [85]:
#find all the instances when the wind speed is above 24 and visibility is 25
df[(df['Wind Speed'] > 24) & (df['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa,Weather_condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [93]:
#mean value of the each columns against each 'Weather condition'
df.groupby('Weather_condition').mean(numeric_only = True) #considering the numeric column only

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa
Weather_condition,,,,,,
Clear,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",20.600000,18.600000,88.000000,19.000000,4.800000,100.080000

In [94]:
#minimum and maximum value of the each column against each weather condition
print(df.groupby('Weather_condition').max())
print(df.groupby('Weather_condition').max())

                                                Date/Time  Temp_C  \
Weather_condition
Clear                                       9/9/2012 5:00    32.8
Cloudy                                     9/9/2012 23:00    30.5
Drizzle                                    9/30/2012 3:00    18.8
Drizzle,Fog                                9/30/2012 2:00    19.9
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00     0.4
Drizzle,Snow                             12/19/2012 18:00     1.2
Drizzle,Snow,Fog                          12/22/2012 3:00     1.1
Fog                                        9/22/2012 0:00    20.8
Freezing Drizzle                            2/1/2012 5:00    -2.3
Freezing Drizzle,Fog                      12/10/2012 5:00    -0.3
Freezing Drizzle,Haze                      2/1/2012 13:00    -5.0
Freezing Drizzle,Snow                      3/2/2012 12:00    -3.3
Freezing Fog                               3/17/2012 6:00    -0.1
Freezing Rain                               2/1/2012 7:00     0.3
Freezing Rain,Fog                         12/17/2012 1:00     0.1
Freezing Rain,Haze                         2/1/2012 15:00    -4.9
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00    -2.6
Freezing Rain,Snow Grains                  1/13/2012 9:00    -5.0
Haze                                      3/13/2012 23:00    14.1
Mainly Clear                                9/9/2012 9:00    33.0
Moderate Rain,Fog                         12/10/2012 8:00     1.7
Moderate Snow                             12/27/2012 9:00    -4.9
Moderate Snow,Blowing Snow               12/27/2012 12:00    -5.4
Mostly Cloudy                               9/9/2012 2:00    32.4
Rain                                        9/5/2012 2:00    22.8
Rain Showers                               9/8/2012 16:00    26.4
Rain Showers,Fog                          10/20/2012 3:00    12.8
Rain Showers,Snow Showers                 12/5/2012 10:00     2.2
Rain,Fog                                  9/30/2012 23:00    21.7
Rain,Haze                                  3/13/2012 9:00     5.5
Rain,Ice Pellets                          12/18/2012 5:00     0.6
Rain,Snow                                  4/23/2012 3:00     1.7
Rain,Snow Grains                          12/21/2012 0:00     1.9
Rain,Snow,Fog                             12/8/2012 21:00     0.8
Rain,Snow,Ice Pellets                     12/21/2012 5:00     1.3
Snow                                       4/27/2012 9:00     3.7
Snow Pellets                             11/24/2012 15:00     0.7
Snow Showers                               3/4/2012 21:00     2.9
Snow Showers,Fog                         12/29/2012 13:00   -10.0
Snow,Blowing Snow                          2/25/2012 9:00    -1.4
Snow,Fog                                  3/14/2012 19:00     1.1
Snow,Haze                                  2/1/2012 21:00    -3.6
Snow,Ice Pellets                            3/3/2012 4:00     0.8
Thunderstorms                              7/4/2012 16:00    26.7
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00    10.9
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00    19.6
Thunderstorms,Rain                        7/23/2012 18:00    21.3
Thunderstorms,Rain Showers                  9/8/2012 4:00    25.5
Thunderstorms,Rain Showers,Fog            7/31/2012 20:00    22.9
Thunderstorms,Rain,Fog                     7/17/2012 5:00    20.6

                                         Dew Point Temp_C  Rel Hum_%  \
Weather_condition
Clear                                                20.4         99
Cloudy                                               22.6         99
Drizzle                                              17.7         96
Drizzle,Fog                                          19.1        100
Drizzle,Ice Pellets,Fog                              -0.7         92
Drizzle,Snow                                          0.2         95
Drizzle,Snow,Fog                                      0.6         98
Fog                                                  19.6        100
Freezing Drizzle                                     -3.3         93
Freezing Drizzle,Fog                                 -2.3         94
Freezing Drizzle,Haze                                -7.7         83
Freezing Drizzle,Snow                                -4.6         94
Freezing Fog                                         -0.3         99
Freezing Rain                                        -1.7         92
Freezing Rain,Fog                                    -0.9         93
Freezing Rain,Haze                                   -7.4         83
Freezing Rain,Ice Pellets,Fog                        -3.7         92
Freezing Rain,Snow Grains                            -7.3         84
Haze                                                 11.1         86
Mainly Clear                                         21.2         99
Moderate Rain,Fog                                     0.8         94
Moderate Snow                                        -6.7         93
Moderate Snow,Blowing Snow                           -6.4         93
Mostly Cloudy                                        24.4        100
Rain                                                 20.4         99
Rain Showers                                         23.0         97
Rain Showers,Fog                                     12.1         96
Rain Showers,Snow Showers                            -1.2         78
Rain,Fog                                             19.5        100
Rain,Haze                                             2.9         86
Rain,Ice Pellets                                     -0.6         92
Rain,Snow                                             0.5         94
Rain,Snow Grains                                     -2.1         75
Rain,Snow,Fog                                         0.3         96
Rain,Snow,Ice Pellets                                 0.1         94
Snow                                                  0.3         96
Snow Pellets                                         -6.4         59
Snow Showers                                         -0.7         94
Snow Showers,Fog                                    -11.1         92
Snow,Blowing Snow                                    -2.9         91
Snow,Fog                                              0.8         99
Snow,Haze                                            -6.4         81
Snow,Ice Pellets                                     -1.7         92
Thunderstorms                                        20.1         87
Thunderstorms,Heavy Rain Showers                      9.0         88
Thunderstorms,Moderate Rain Showers,Fog              18.5         93
Thunderstorms,Rain                                   19.1         93
Thunderstorms,Rain Showers                           23.1         98
Thunderstorms,Rain Showers,Fog                       21.3         91
Thunderstorms,Rain,Fog                               18.6         88

                                         Wind Speed  Visibility_km  Press_kPa
Weather_condition
Clear                                            33           48.3     103.63
Cloudy                                           54           48.3     103.65
Drizzle                                          30           25.0     101.56
Drizzle,Fog                                      28            9.7     102.07
Drizzle,Ice Pellets,Fog                          20            4.0     100.79
Drizzle,Snow                                     19           11.3     101.15
Drizzle,Snow,Fog                                 32            9.7     100.15
Fog                                              22            9.7     103.04
Freezing Drizzle                                 26           12.9     101.02
Freezing Drizzle,Fog                             33            8.0     101.27
Freezing Drizzle,Haze                            11            4.0     100.36
Freezing Drizzle,Snow                            24           12.9     101.18
Freezing Fog                                      9            0.8     102.85
Freezing Rain                                    28           16.1     101.00
Freezing Rain,Fog                                26            9.7     101.01
Freezing Rain,Haze                                9            2.8     100.41
Freezing Rain,Ice Pellets,Fog                    28            8.0     100.95
Freezing Rain,Snow Grains                        32            4.8      98.56
Haze                                             17            9.7     102.97
Mainly Clear                                     63           48.3     103.59
Moderate Rain,Fog                                17            6.4      99.98
Moderate Snow                                    39            0.8     100.67
Moderate Snow,Blowing Snow                       41            0.6     100.64
Mostly Cloudy                                    83           48.3     103.65
Rain                                             52           48.3     102.26
Rain Showers                                     41           48.3     102.31
Rain Showers,Fog                                 13            6.4      99.83
Rain Showers,Snow Showers                        28           24.1     101.11
Rain,Fog                                         46            9.7     101.77
Rain,Haze                                        17            9.7     100.61
Rain,Ice Pellets                                 24            9.7     100.12
Rain,Snow                                        52           25.0     101.07
Rain,Snow Grains                                 26           25.0     100.60
Rain,Snow,Fog                                     9            6.4     100.73
Rain,Snow,Ice Pellets                            28            6.4     100.47
Snow                                             57           25.0     102.73
Snow Pellets                                     35            2.4      99.70
Snow Showers                                     37           48.3     102.50
Snow Showers,Fog                                 22            9.7     102.52
Snow,Blowing Snow                                48            9.7     100.62
Snow,Fog                                         35            9.7     102.07
Snow,Haze                                        15            6.4     100.99
Snow,Ice Pellets                                 33           11.3     100.96
Thunderstorms                                    15           25.0     100.62
Thunderstorms,Heavy Rain Showers                  9            2.4     100.26
Thunderstorms,Moderate Rain Showers,Fog          15            3.2     100.01
Thunderstorms,Rain                               30           24.1     100.83
Thunderstorms,Rain Showers                       32           25.0     101.06
Thunderstorms,Rain Showers,Fog                   35            9.7     100.64
Thunderstorms,Rain,Fog                           19            4.8     100.08
                                                Date/Time  Temp_C  \
Weather_condition
Clear                                       9/9/2012 5:00    32.8
Cloudy                                     9/9/2012 23:00    30.5
Drizzle                                    9/30/2012 3:00    18.8
Drizzle,Fog                                9/30/2012 2:00    19.9
Drizzle,Ice Pellets,Fog                   12/17/2012 9:00     0.4
Drizzle,Snow                             12/19/2012 18:00     1.2
Drizzle,Snow,Fog                          12/22/2012 3:00     1.1
Fog                                        9/22/2012 0:00    20.8
Freezing Drizzle                            2/1/2012 5:00    -2.3
Freezing Drizzle,Fog                      12/10/2012 5:00    -0.3
Freezing Drizzle,Haze                      2/1/2012 13:00    -5.0
Freezing Drizzle,Snow                      3/2/2012 12:00    -3.3
Freezing Fog                               3/17/2012 6:00    -0.1
Freezing Rain                               2/1/2012 7:00     0.3
Freezing Rain,Fog                         12/17/2012 1:00     0.1
Freezing Rain,Haze                         2/1/2012 15:00    -4.9
Freezing Rain,Ice Pellets,Fog             12/17/2012 3:00    -2.6
Freezing Rain,Snow Grains                  1/13/2012 9:00    -5.0
Haze                                      3/13/2012 23:00    14.1
Mainly Clear                                9/9/2012 9:00    33.0
Moderate Rain,Fog                         12/10/2012 8:00     1.7
Moderate Snow                             12/27/2012 9:00    -4.9
Moderate Snow,Blowing Snow               12/27/2012 12:00    -5.4
Mostly Cloudy                               9/9/2012 2:00    32.4
Rain                                        9/5/2012 2:00    22.8
Rain Showers                               9/8/2012 16:00    26.4
Rain Showers,Fog                          10/20/2012 3:00    12.8
Rain Showers,Snow Showers                 12/5/2012 10:00     2.2
Rain,Fog                                  9/30/2012 23:00    21.7
Rain,Haze                                  3/13/2012 9:00     5.5
Rain,Ice Pellets                          12/18/2012 5:00     0.6
Rain,Snow                                  4/23/2012 3:00     1.7
Rain,Snow Grains                          12/21/2012 0:00     1.9
Rain,Snow,Fog                             12/8/2012 21:00     0.8
Rain,Snow,Ice Pellets                     12/21/2012 5:00     1.3
Snow                                       4/27/2012 9:00     3.7
Snow Pellets                             11/24/2012 15:00     0.7
Snow Showers                               3/4/2012 21:00     2.9
Snow Showers,Fog                         12/29/2012 13:00   -10.0
Snow,Blowing Snow                          2/25/2012 9:00    -1.4
Snow,Fog                                  3/14/2012 19:00     1.1
Snow,Haze                                  2/1/2012 21:00    -3.6
Snow,Ice Pellets                            3/3/2012 4:00     0.8
Thunderstorms                              7/4/2012 16:00    26.7
Thunderstorms,Heavy Rain Showers           5/29/2012 6:00    10.9
Thunderstorms,Moderate Rain Showers,Fog    7/17/2012 6:00    19.6
Thunderstorms,Rain                        7/23/2012 18:00    21.3
Thunderstorms,Rain Showers                  9/8/2012 4:00    25.5
Thunderstorms,Rain Showers,Fog            7/31/2012 20:00    22.9
Thunderstorms,Rain,Fog                     7/17/2012 5:00    20.6

                                         Dew Point Temp_C  Rel Hum_%  \
Weather_condition
Clear                                                20.4         99
Cloudy                                               22.6         99
Drizzle                                              17.7         96
Drizzle,Fog                                          19.1        100
Drizzle,Ice Pellets,Fog                              -0.7         92
Drizzle,Snow                                          0.2         95
Drizzle,Snow,Fog                                      0.6         98
Fog                                                  19.6        100
Freezing Drizzle                                     -3.3         93
Freezing Drizzle,Fog                                 -2.3         94
Freezing Drizzle,Haze                                -7.7         83
Freezing Drizzle,Snow                                -4.6         94
Freezing Fog                                         -0.3         99
Freezing Rain                                        -1.7         92
Freezing Rain,Fog                                    -0.9         93
Freezing Rain,Haze                                   -7.4         83
Freezing Rain,Ice Pellets,Fog                        -3.7         92
Freezing Rain,Snow Grains                            -7.3         84
Haze                                                 11.1         86
Mainly Clear                                         21.2         99
Moderate Rain,Fog                                     0.8         94
Moderate Snow                                        -6.7         93
Moderate Snow,Blowing Snow                           -6.4         93
Mostly Cloudy                                        24.4        100
Rain                                                 20.4         99
Rain Showers                                         23.0         97
Rain Showers,Fog                                     12.1         96
Rain Showers,Snow Showers                            -1.2         78
Rain,Fog                                             19.5        100
Rain,Haze                                             2.9         86
Rain,Ice Pellets                                     -0.6         92
Rain,Snow                                             0.5         94
Rain,Snow Grains                                     -2.1         75
Rain,Snow,Fog                                         0.3         96
Rain,Snow,Ice Pellets                                 0.1         94
Snow                                                  0.3         96
Snow Pellets                                         -6.4         59
Snow Showers                                         -0.7         94
Snow Showers,Fog                                    -11.1         92
Snow,Blowing Snow                                    -2.9         91
Snow,Fog                                              0.8         99
Snow,Haze                                            -6.4         81
Snow,Ice Pellets                                     -1.7         92
Thunderstorms                                        20.1         87
Thunderstorms,Heavy Rain Showers                      9.0         88
Thunderstorms,Moderate Rain Showers,Fog              18.5         93
Thunderstorms,Rain                                   19.1         93
Thunderstorms,Rain Showers                           23.1         98
Thunderstorms,Rain Showers,Fog                       21.3         91
Thunderstorms,Rain,Fog                               18.6         88

                                         Wind Speed  Visibility_km  Press_kPa
Weather_condition
Clear                                            33           48.3     103.63
Cloudy                                           54           48.3     103.65
Drizzle                                          30           25.0     101.56
Drizzle,Fog                                      28            9.7     102.07
Drizzle,Ice Pellets,Fog                          20            4.0     100.79
Drizzle,Snow                                     19           11.3     101.15
Drizzle,Snow,Fog                                 32            9.7     100.15
Fog                                              22            9.7     103.04
Freezing Drizzle                                 26           12.9     101.02
Freezing Drizzle,Fog                             33            8.0     101.27
Freezing Drizzle,Haze                            11            4.0     100.36
Freezing Drizzle,Snow                            24           12.9     101.18
Freezing Fog                                      9            0.8     102.85
Freezing Rain                                    28           16.1     101.00
Freezing Rain,Fog                                26            9.7     101.01
Freezing Rain,Haze                                9            2.8     100.41
Freezing Rain,Ice Pellets,Fog                    28            8.0     100.95
Freezing Rain,Snow Grains                        32            4.8      98.56
Haze                                             17            9.7     102.97
Mainly Clear                                     63           48.3     103.59
Moderate Rain,Fog                                17            6.4      99.98
Moderate Snow                                    39            0.8     100.67
Moderate Snow,Blowing Snow                       41            0.6     100.64
Mostly Cloudy                                    83           48.3     103.65
Rain                                             52           48.3     102.26
Rain Showers                                     41           48.3     102.31

In [95]:
#show all the records where the weather condition is Fog
df[df['Weather_condition'] == 'Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa,Weather_condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90,7,6.4,101.15,Fog

In [89]:
#find all instances when the weather is clear or visibility is above 40

In [107]:
#changing the Date/Time column to the datetime format
# df['Date-time'] = pd.to_datetime(df['Date/Time'])
# df['Date-time']

In [109]:
#setting the index as Date-time column
# df.set_index('Date-time', inplace = True)
# df

In [105]:
df.drop(columns= 'Date/Time',inplace = True)
df

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa,Weather_condition
Date-time,,,,,,,
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...
2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [111]:
#find all the instance when the weather is clear or visibility is above 40.
df[(df['Weather_condition'] == 'Clear') | (df['Visibility_km'] >40)]

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa,Weather_condition
Date-time,,,,,,,
2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
2012-01-05 10:00:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
2012-01-05 11:00:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
2012-01-05 12:00:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
2012-01-05 13:00:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...
2012-12-30 13:00:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
2012-12-30 14:00:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
2012-12-30 15:00:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
2012-12-30 16:00:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [118]:
#find all the instance when the relative humdity is greater than 50
df[((df['Weather_condition'] == 'Clear') & (df['Rel Hum_%'] >40)) |
    (df['Visibility_km']>40)]

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed,Visibility_km,Press_kPa,Weather_condition
Date-time,,,,,,,
2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
2012-01-05 10:00:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
2012-01-05 11:00:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
2012-01-05 12:00:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
2012-01-05 13:00:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...
2012-12-30 13:00:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
2012-12-30 14:00:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
2012-12-30 15:00:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
2012-12-30 16:00:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear